direction: down

start: "Mulai IsValidPackageType" {
  shape: oval
}

loop_start: "Ambil next validType dari PackageTypes" {
  shape: rectangle
}

check_match: "Apakah validType == packageType?" {
  shape: diamond
}

return_true: "Kembalikan true" {
  shape: oval
}

loop_end: "Selesai perulangan?" {
  shape: diamond
}

return_false: "Kembalikan false" {
  shape: oval
}

end: "Selesai fungsi" {
  shape: oval
}

start -> loop_start -> check_match
check_match -> return_true: Ya
check_match -> loop_end: Tidak
loop_end -> loop_start: Tidak
loop_end -> return_false: Ya
return_true -> end
return_false -> end
