direction: down

start: "Mulai UpdateStatus" {
  shape: oval
}

clear: "Clear Screen" {
  shape: rectangle
}

getUsername: "Ambil username login" {
  shape: rectangle
}

filterPaket: "Ambil paket milik kurir (filterPaketByKurir)" {
  shape: rectangle
}

cekKosong: "Apakah paketList kosong?" {
  shape: diamond
}

showTidakAda: "Tampilkan 'tidak ada paket'" {
  shape: rectangle
}

returnKosong: "utils.EnterToContinue()\nreturn" {
  shape: rectangle
}

tampilkanDaftar: "Tampilkan daftar paket & status terakhir" {
  shape: rectangle
}

inputPaket: "Input nomor paket" {
  shape: parallelogram
}

validasiPaket: "Apakah input valid?" {
  shape: diamond
}

returnPaketInvalid: "Tampilkan 'Pilihan tidak valid.'\nreturn" {
  shape: rectangle
}

tampilkanStatus: "Tampilkan pilihan status baru" {
  shape: rectangle
}

inputStatus: "Input nomor status baru" {
  shape: parallelogram
}

validasiStatus: "Apakah input status valid?" {
  shape: diamond
}

returnStatusInvalid: "Tampilkan 'Status tidak valid.'\nreturn" {
  shape: rectangle
}

konfirmasi: "Konfirmasi perubahan status (y/n)" {
  shape: parallelogram
}

cekKonfirmasi: "Apakah jawabannya 'y'?" {
  shape: diamond
}

dibatalkan: "Tampilkan 'dibatalkan'\nEnterToContinue\nreturn" {
  shape: rectangle
}

update: "updateStatusPaket()\n& tampilkan hasilnya" {
  shape: rectangle
}

waitEnter: "utils.EnterToContinue()" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> clear -> getUsername -> filterPaket -> cekKosong
cekKosong -> showTidakAda: Ya
showTidakAda -> returnKosong -> end

cekKosong -> tampilkanDaftar: Tidak
tampilkanDaftar -> inputPaket -> validasiPaket

validasiPaket -> returnPaketInvalid: Tidak
validasiPaket -> tampilkanStatus: Ya

tampilkanStatus -> inputStatus -> validasiStatus
validasiStatus -> returnStatusInvalid: Tidak
validasiStatus -> konfirmasi: Ya

konfirmasi -> cekKonfirmasi
cekKonfirmasi -> dibatalkan: Tidak
cekKonfirmasi -> update: Ya

update -> waitEnter -> end
dibatalkan -> end
