direction: down

start: "Mulai MenuKurir()" {
  shape: oval
}

clearScreen: "Clear screen" {
  shape: rectangle
}

printHeader: "Cetak header menu kurir" {
  shape: rectangle
}

printOptions: "Cetak opsi menu:\n1. Lihat Assigned Paket\n2. Update Status Paket\n0. Logout" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> clearScreen -> printHeader -> printOptions -> end
