direction: down

start: "Mulai FindUserByUsername(username)" {
  shape: oval
}

loop: "Loop setiap user di datas.UsersDB" {
  shape: rectangle
}

cekUsername: "Apakah user.Username == username?" {
  shape: diamond
}

returnUser: "return user" {
  shape: rectangle
}

returnEmpty: "return types.User{}" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> loop -> cekUsername
cekUsername -> returnUser: Ya
returnUser -> end
cekUsername -> loop: Tidak
loop -> returnEmpty
returnEmpty -> end
