direction: down

start: "Mulai ShowDelayedMessage(message, delay, clearScreen)" {
  shape: oval
}

cekClearBefore: "clearScreen == true?" {
  shape: diamond
}

clearScreenBefore: "Panggil ClearScreen()" {
  shape: rectangle
}

loopStart: "Loop i dari 0 sampai delay-1" {
  shape: rectangle
}

clearScreenLoop: "Panggil ClearScreen()" {
  shape: rectangle
}

printMessage: "Tampilkan message" {
  shape: rectangle
}

sleep1s: "time.Sleep(1 detik)" {
  shape: rectangle
}

cekClearAfter: "clearScreen == true?" {
  shape: diamond
}

clearScreenAfter: "Panggil ClearScreen()" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> cekClearBefore
cekClearBefore -> clearScreenBefore: Ya
cekClearBefore -> loopStart: Tidak
clearScreenBefore -> loopStart

loopStart -> clearScreenLoop -> printMessage -> sleep1s -> loopStart

loopStart -> cekClearAfter

cekClearAfter -> clearScreenAfter: Ya
cekClearAfter -> end: Tidak
clearScreenAfter -> end
