printNoPackage: {
  label: "printNoPackage()"
  shape: rectangle
}

judul: {
  label: "Tampilkan Judul:\n📦 DAFTAR PAKET ANDA"
  shape: rectangle
}

isi: {
  label: "Tampilkan Pesan:\nTidak ada paket yang sedang Anda tangani."
  shape: rectangle
}

printNoPackage -> judul -> isi
