direction: down

start: "Mulai UpdatePaket(paket)" {
  shape: oval
}

loop: "Loop setiap paket di datas.PaketDB" {
  shape: rectangle
}

cekNoResi: "Apakah p.NoResi == paket.NoResi?" {
  shape: diamond
}

updateData: "Ganti datas.PaketDB[i] dengan paket baru" {
  shape: rectangle
}

return: "return (keluar dari fungsi)" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> loop -> cekNoResi
cekNoResi -> updateData: Ya
updateData -> return -> end
cekNoResi -> loop: Tidak
loop -> end
