direction: down

start: "Mulai SetLoggedInUsername(username)" {
  shape: oval
}

setUsername: "Set loggedInUsername = username" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> setUsername -> end
