direction: down

start: "Mulai GetLoggedInUsername()" {
  shape: oval
}

returnUsername: "Return loggedInUsername" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> returnUsername -> end
