direction: down

start: "Mulai InputCity(prompt)" {
  shape: oval
}

tampilkanPrompt: "Tampilkan prompt & daftar kota dari types.Kota" {
  shape: rectangle
}

inputCityName: "Minta input cityName dari user" {
  shape: rectangle
}

cekInputKosong: "Apakah input kosong?" {
  shape: diamond
}

tampilkanErrorKosong: "Tampilkan pesan 'Kota tidak boleh kosong.'" {
  shape: rectangle
}

validasiKota: "Cek apakah cityName valid di types.Kota?" {
  shape: diamond
}

returnErrorKotaTidakDitemukan: "Return error 'kota tidak ditemukan'" {
  shape: rectangle
}

cariKoordinat: "Cari koordinat di types.DaftarTempat berdasarkan cityName" {
  shape: rectangle
}

ketemuKoordinat: "Apakah koordinat ditemukan?" {
  shape: diamond
}

returnKoordinat: "Return types.Tempat" {
  shape: oval
}

returnErrorKoordinatTidakDitemukan: "Return error 'koordinat tidak ditemukan'" {
  shape: rectangle
}

start -> tampilkanPrompt -> inputCityName -> cekInputKosong
cekInputKosong -> tampilkanErrorKosong: Ya
tampilkanErrorKosong -> inputCityName
cekInputKosong -> validasiKota: Tidak
validasiKota -> returnErrorKotaTidakDitemukan: Tidak
validasiKota -> cariKoordinat: Ya
cariKoordinat -> ketemuKoordinat
ketemuKoordinat -> returnKoordinat: Ya
ketemuKoordinat -> returnErrorKoordinatTidakDitemukan: Tidak
