EnterToContinue: {
  label: "EnterToContinue()"
  shape: rectangle
}

CallGetInput: {
  label: "utils.GetInput(...)"
  shape: rectangle
  style: {
    stroke-dash: 3
  }
}

EnterToContinue -> CallGetInput