direction: down

start: "Mulai TambahPaket()" {
  shape: oval
}

clearScreen: "utils.ClearScreen()" {
  shape: rectangle
}

inputTipe: "tipe, err := InputPackageType()" {
  shape: rectangle
}

checkErrTipe: "err != nil?" {
  shape: diamond
}

printErrTipe: "fmt.Println(err.Error())" {
  shape: rectangle
}

endEarly1: "Return" {
  shape: oval
}

inputBerat: "Input berat paket (kg)" {
  shape: rectangle
}

inputSenderCity: "senderCity, err := InputCity('Kota Pengirim')" {
  shape: rectangle
}

checkErrSenderCity: "err != nil?" {
  shape: diamond
}

printErrSenderCity: "fmt.Println(err.Error())" {
  shape: rectangle
}

endEarly2: "Return" {
  shape: oval
}

inputReceiverCity: "receiverCity, err := InputCity('Kota Tujuan')" {
  shape: rectangle
}

checkErrReceiverCity: "err != nil?" {
  shape: diamond
}

printErrReceiverCity: "fmt.Println(err.Error())" {
  shape: rectangle
}

endEarly3: "Return" {
  shape: oval
}

calcPrice: "distance, price := CalculatePackagePrice(...)" {
  shape: rectangle
}

printDistance: "Print jarak antar kota" {
  shape: rectangle
}

printPrice: "Print harga paket" {
  shape: rectangle
}

confirmAdd: "Confirm('Apakah Anda yakin...?')" {
  shape: diamond
}

printNotAdded: "fmt.Println('Paket tidak ditambahkan.')" {
  shape: rectangle
}

endEarly4: "Return" {
  shape: oval
}

createPackage: "Buat struct Paket baru" {
  shape: rectangle
}

appendPackage: "Tambahkan paket ke datas.PaketDB" {
  shape: rectangle
}

printSuccess: "fmt.Println('Paket berhasil ditambahkan.')" {
  shape: rectangle
}

callDetail: "DetailPaket(input)" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> clearScreen -> inputTipe -> checkErrTipe
checkErrTipe -> printErrTipe: Ya
printErrTipe -> endEarly1
checkErrTipe -> inputBerat: Tidak

inputBerat -> inputSenderCity -> checkErrSenderCity
checkErrSenderCity -> printErrSenderCity: Ya
printErrSenderCity -> endEarly2
checkErrSenderCity -> inputReceiverCity: Tidak

inputReceiverCity -> checkErrReceiverCity
checkErrReceiverCity -> printErrReceiverCity: Ya
printErrReceiverCity -> endEarly3
checkErrReceiverCity -> calcPrice: Tidak

calcPrice -> printDistance -> printPrice -> confirmAdd
confirmAdd -> printNotAdded: Tidak
printNotAdded -> endEarly4
confirmAdd -> createPackage: Ya

createPackage -> appendPackage -> printSuccess -> callDetail -> end
