direction: down

start: "Mulai HapusPaket()" {
  shape: oval
}

clearScreen: "Panggil utils.ClearScreen()" {
  shape: rectangle
}

printHeader: "Cetak '=== Hapus Paket ==='" {
  shape: rectangle
}

inputNoResi: "Input No Resi paket" {
  shape: rectangle
}

deletePaket: "Panggil utils.DeletePaket(noResi)" {
  shape: rectangle
}

checkOk: "Apakah ok == true?" {
  shape: diamond
}

printFailed: "Cetak 'Paket tidak dapat dihapus. No Resi tidak ditemukan.'" {
  shape: rectangle
}

printSuccess: "Cetak 'Paket dengan No Resi %s telah dihapus.'" {
  shape: rectangle
}

enterToContinue: "Panggil utils.EnterToContinue()" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> clearScreen -> printHeader -> inputNoResi -> deletePaket -> checkOk
checkOk -> printSuccess: Ya
checkOk -> printFailed: Tidak
printFailed -> end
printSuccess -> enterToContinue -> end
