direction: down

start: "Mulai MenuUser()" {
  shape: oval
}

clearScreen: "utils.ClearScreen()" {
  shape: rectangle
}

getUsername: "Ambil username yang login" {
  shape: rectangle
}

printHeader: "Tampilkan header dan salam" {
  shape: rectangle
}

printMenu: "Tampilkan pilihan menu:\n1. Tambah Paket\n2. Cek Paket\n0. Logout" {
  shape: rectangle
}

end: "Selesai" {
  shape: oval
}

start -> clearScreen -> getUsername -> printHeader -> printMenu -> end
