# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "john-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./...

    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: PackageDelivery
        path: ./PackageDelivery
  
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./...

    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: PackageDelivery
        path: PackageDelivery.exe