name: CLI Screenshot CI

on:
  push:
    branches:
      - main
      - testing-autogen-manual
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    # tell every step to use the virtual display
    env:
      DISPLAY: :99

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            expect \
            xdotool \
            golang \
            scrot \
            xterm \
            imagemagick \
            fonts-noto-color-emoji \
            fontconfig \
            fonts-noto \
            fonts-noto-color-emoji \
            fonts-symbola \
            xvfb
    
      - name: Rebuild font cache
        run: fc-cache -f -v


      - name: Write emoji‐first fontconfig
        run: |
          mkdir -p ~/.config/fontconfig
          cat << 'EOF' > ~/.config/fontconfig/fonts.conf
          <?xml version="1.0"?>
          <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
          <fontconfig>
            <!-- prefer Noto Color Emoji for any sans-serif/serif/fallback -->
            <alias>
              <family>sans-serif</family>
              <prefer>
                <family>Noto Color Emoji</family>
              </prefer>
            </alias>
            <alias>
              <family>serif</family>
              <prefer>
                <family>Noto Color Emoji</family>
              </prefer>
            </alias>
          </fontconfig>
          EOF
          fc-cache -f -v


      - name: Start headless X server
        run: |
          # launch Xvfb on display :99 in the background
          Xvfb :99 -screen 0 800x600x24 &

      - name: Build the application
        run: |
          go build .

      - name: Run CLI test script
        run: |
          chmod +x test_snapshot.sh
          mkdir -p logs
          # Launch an xterm on DISPLAY, tell it to run bash -lc "./test_snapshot.sh", then exit
          xterm \
            -display $DISPLAY \
            -xrm 'XTerm*faceName: Noto Mono' \
            -xrm 'XTerm*faceSize: 14' \
            -xrm 'XTerm*renderFont: true' \
            -xrm 'XTerm*enableMultiByte: true' \
            -fa "Noto Mono" \
            -fs 14 \
            -geometry 80x24+0+0 \
            -e bash -lc "./test_snapshot.sh" &
          wait

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cli-screenshots
          path: logs/
