name: CLI Recording CI

on:
  push:
    branches:
      - main
      - testing-autogen-manual
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            expect \
            asciinema

      - name: Install svg-term CLI
        run: npm install --global svg-term-cli

      - name: Build the Go CLI
        run: go build .

      - name: Record CLI session with Asciinema
        run: |
          mkdir -p logs
          # -q = quiet, -c = command
          asciinema rec -q -c "./test_snapshot.sh" logs/session.json

      - name: Render session to SVG
        run: |
          svg-term \
            --in logs/session.json \
            --out logs/session.svg \
            --window \
            --padding 10 \
            --profile nord \
            --size 80x24

      - name: Render session to PNG
        run: |
          svg-term \
            --in logs/session.json \
            --out logs/session.png \
            --window \
            --padding 10 \
            --profile nord \
            --size 80x24 \
            --format png

      - name: Upload recording artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-recording
          path: |
            logs/session.json
            logs/session.svg
            logs/session.png
