name: CLI Screenshot CI

on:
  push:
    branches:
      - main
      - testing-autogen-manual
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    # tell every step to use the virtual display
    env:
      DISPLAY: :99

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            expect \
            xdotool \
            golang \
            scrot \
            xterm \
            imagemagick \
            fonts-noto-color-emoji \
            xvfb

      - name: Start headless X server
        run: |
          # launch Xvfb on display :99 in the background
          Xvfb :99 -screen 0 800x600x24 &

      - name: Build the application
        run: |
          go build .

      - name: Run CLI test script
        run: |
          chmod +x test_snapshot.sh
          mkdir -p logs
          # Launch an xterm on DISPLAY, tell it to run bash -lc "./test_snapshot.sh", then exit
          xterm \
            -display $DISPLAY \
            -fa "Noto Mono" \
            -fs 14 \
            -geometry 80x24+0+0 \
            -e bash -lc "./test_snapshot.sh" &
          wait

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cli-screenshots
          path: logs/
