name: CLI Recording CI

on:
  push:
    branches:
      - main
      - testing-autogen-manual
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            expect \
            asciinema \
            imagemagick

      - name: Install svg-term-cli & update PATH
        run: |
          npm install --global svg-term-cli
          echo "PATH=$(npm bin -g):$PATH" >> $GITHUB_ENV

      - name: Build the Go CLI
        run: go build .

      - name: Record CLI session with Asciinema
        run: |
          mkdir -p logs
          # Launch an xterm on DISPLAY, tell it to run bash -lc "./test_snapshot.sh", then exit
          xterm \
            -display $DISPLAY \
            -fa "Noto Mono" \
            -fs 14 \
            -geometry 80x24+0+0 \
            -e bash -lc "./test_snapshot.sh" &
          wait

      - name: Render session to SVG
        run: |
          svg-term \
            --in logs/session.json \
            --out logs/session.svg \
            --window \
            --padding 10 \
            --width 80 \
            --height 24 \
            --term terminal \
            --profile nord

      - name: Convert SVG to PNG
        run: |
          convert -background white logs/session.svg logs/session.png

      - name: Upload recording artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-recording
          path: |
            logs/session.json
            logs/session.svg
            logs/session.png
